In [1]:
import sys
sys.path.append("../script/")

import Functions
from Engine import Engine
from GTGP import GTGP


from sklearn.metrics import classification_report,accuracy_score,confusion_matrix,f1_score

from sklearn.model_selection import train_test_split
import numpy as np
import importlib
from time import time
from matplotlib import pyplot as plt
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
import numpy as np
import pandas as pd
from time import time

In [2]:
from sklearn.metrics import roc_auc_score, roc_curve
from sklearn.utils import shuffle
def plot_roc_curve(true_y, y_prob):
    """
    plots the roc curve based of the probabilities
    """
    
    fpr, tpr, thresholds = roc_curve(true_y, y_prob)
    plt.plot(fpr, tpr)
    plt.xlabel('False Positive Rate')
    plt.ylabel('True Positive Rate')
    print(roc_auc_score(true_y,prob[:,1]))

# data

In [3]:
df = pd.read_csv("../data/sleep.tsv",delimiter='\t')
X = df.iloc[:,:-1].to_numpy().astype("float")
y = df.iloc[:,-1].to_numpy().astype("int")
y[y==5] = 4


seeds = [10086, 200,500,30506,30405,30420,10056,7059,40965,5398,869543,83491,823190,
         48392,2810,48392,3498210,483902,859032,12890,538920,86954,54309,6504,9840,
         219805,548,2981,432890,5438908,219094,5843902,60854,979,12890,2108,4093]
train_size = 0.7
dataset = 'sleep'

X_train,X_test,y_train,y_test = train_test_split(X,y,train_size=train_size,stratify=y)

# model

In [4]:
def retain(gtgp):
    retrain_epoch=10
    alpha=0
    beta=1
    gammer=0

    verbose=1
    gtgp.lam = 10
    gtgp.retrain_estimators(X_test,y_test,retrain_epoch=retrain_epoch,alpha=alpha,beta=beta,gammer=gammer,verbose=verbose)

    return gtgp

retain(gtgp)

NameError: name 'gtgp' is not defined

In [5]:
def fit_trees():
    learning_rate=0.3
    max_depth=1
    bins=8
    lam=1

    gtgp = GTGP(learning_rate=learning_rate,max_depth=max_depth,bins=bins,lam=lam)

    total_size=10
    elite_size = 10
    epoch= 1
    gp_epoch= 3
    verbose = 1
    tolerance=0.001

    gtgp.fit(X_train,y_train,total_size=total_size,elite_size = elite_size,epoch=epoch,gp_epoch=gp_epoch,tolerance=tolerance,verbose=verbose)
    return gtgp

def retain(gtgp):
    retrain_epoch=10
    alpha=0
    beta=1
    gammer=0

    verbose=1
    gtgp.lam = 10
    gtgp.retrain_estimators(X_test,y_test,retrain_epoch=retrain_epoch,alpha=alpha,beta=beta,gammer=gammer,verbose=verbose)

    return gtgp

for i in range(1):
    X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=train_size,stratify=y, random_state=seeds[i])
    gtgp = fit_trees()
    retain(gtgp)

    print(classification_report(y_train,np.argmax(gtgp.train_p,axis=1),digits=5))
    print(classification_report(y_test,np.argmax(gtgp.test_p,axis=1),digits=5))

    num_trees,depth,num_nodes = gtgp.print_model()

    train_acc = accuracy_score(y_train,np.argmax(gtgp.train_p,axis=1))
    test_acc = accuracy_score(y_test,np.argmax(gtgp.test_p,axis=1))
    train_f1 = f1_score(y_train,np.argmax(gtgp.train_p,axis=1),average='macro')
    test_f1 = f1_score(y_test,np.argmax(gtgp.test_p,axis=1),average='macro')


    # with open('./benchmark/'+dataset+'.csv','a') as f:
    #     s = str(train_acc)+","+str(test_acc)+","+str(train_f1)+","+str(test_f1)+","+str(num_trees)+","+str(depth)+","+str(num_nodes)+"\n"
    #     f.writelines(s)

28 122 1
retrain  1 :
	train: 0.6497470830242126 0.3990229887379425 	test: 0.6493248984987253 0.39879506527756287
retrain  2 :
	train: 0.6535239765293046 0.40823787678276036 	test: 0.6525981178988449 0.40620264801244704
retrain  3 :
	train: 0.6590948944493155 0.42755470632055914 	test: 0.6582947785855915 0.42538709558448495
retrain  4 :
	train: 0.6620489647265124 0.43640924919507 	test: 0.6609070594529947 0.43364472961588413
retrain  5 :
	train: 0.663343899642544 0.4411088795108114 	test: 0.6627639819972933 0.4395947205036336
retrain  6 :
	train: 0.6652053685843394 0.4511838854313899 	test: 0.664211752116577 0.4489014570120501
retrain  7 :
	train: 0.6668105483240035 0.4581762468985823 	test: 0.6659113083435622 0.45657986837812636
retrain  8 :
	train: 0.6674849935927699 0.4593757235512254 	test: 0.666226040978189 0.4574517809520359
retrain  9 :
	train: 0.6675929048357726 0.45948248757406873 	test: 0.6661945677147263 0.45745131720542337
retrain  10 :
	train: 0.6681189721454104 0.45999049

c:\Users\zhouz\anaconda3\envs\BStackGP\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\zhouz\anaconda3\envs\BStackGP\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\zhouz\anaconda3\envs\BStackGP\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\zhou

In [77]:
p = gtgp.train_p
y_one_hot = gtgp.y_one_hot
index = gtgp.stack[0].estimator.index

terminals = gtgp.stack[0].estimator.terminals

sum_p = np.stack([np.sum(p[index==i],axis=0) for i in terminals])
sum_y = np.stack([np.sum(y_one_hot[index==i],axis=0) for i in terminals])

In [78]:
np.stack([np.sum(y_one_hot[index==i]-p[index==i],axis=0) for i in terminals])

matrix([[-11.0365206 ,  -5.02315701, -46.29262031,   1.30415642,
         -22.72807689],
        [ 11.07255465,   4.89441752,  46.30519919,  -2.1753474 ,
          22.22439906]])

In [79]:
np.stack([np.sum(np.multiply(p[index==i],1-p[index==i]),axis=0) for i in terminals])

array([[2.32864922e+03, 1.74042932e+03, 1.46320981e+03, 9.38703707e+00,
        4.81858647e+02],
       [4.55101364e+03, 3.79933609e+03, 1.22006662e+04, 5.32473209e+03,
        4.04351631e+03]])

In [112]:
g = []
h = []

for i in terminals:
    p_i = p[index==i]
    p_i_sum = p[index==i].sum(axis=0)
    y_i_sum = y_one_hot[index==i].sum(axis=0)

    g.append(y_i_sum - p_i_sum)
    # h = (p_1*(1-p_1)).sum(axis=0)
    # h = (p_1-p_1**2).sum(axis=0)
    h.append(p_i_sum - (p_i**2).sum(axis=0))
g = np.stack(g)
h = np.stack(h)
w = g/h
g,h,g/h

(matrix([[-11.0365206 ,  -5.02315701, -46.29262031,   1.30415642,
          -22.72807689],
         [ 11.07255465,   4.89441752,  46.30519918,  -2.1753474 ,
           22.22439906]]),
 array([[2.32864922e+03, 1.74042932e+03, 1.46320981e+03, 9.38703707e+00,
         4.81858647e+02],
        [4.55101364e+03, 3.79933609e+03, 1.22006662e+04, 5.32473209e+03,
         4.04351631e+03]]),
 matrix([[-0.00473945, -0.00288616, -0.03163772,  0.13893164, -0.04716752],
         [ 0.00243299,  0.00128823,  0.0037953 , -0.00040854,  0.00549631]]))

In [59]:
gtgp.stack[0].estimator

In [10]:
retrain_epoch=100
alpha=1
beta=1
gammer=0

verbose=1
gtgp.lam = 10
train_acc,test_acc,train_sse,test_sse = gtgp.retrain_estimators(X_test,y_test,retrain_epoch=retrain_epoch,alpha=alpha,beta=beta,gammer=gammer,verbose=verbose)


# verbose=0
# gtgp.retrain_estimators(retrain_epoch=retrain_epoch,alpha=alpha,beta=beta,gammer=gammer,verbose=verbose)

retrain  1 :
	train: 0.7548661226141499 0.6274821919551506 	test: 0.7488748308312089 0.6214189032970736
retrain  2 :
	train: 0.7618668645039455 0.6400869652166759 	test: 0.7529978283448211 0.6307157135406192
retrain  3 :
	train: 0.764348823093006 0.6451088634314445 	test: 0.7550750637333585 0.6350920933811953
retrain  4 :
	train: 0.7661023807917987 0.6485553497406842 	test: 0.7545400182544928 0.6352291517043385
retrain  5 :
	train: 0.7671680043164497 0.6513021685292547 	test: 0.7551065369968212 0.6374691157705026
retrain  6 :
	train: 0.768125716598098 0.6532198801134952 	test: 0.7554527428949108 0.6384632012484118
retrain  7 :
	train: 0.7685978282862346 0.6545265911166034 	test: 0.7557674755295376 0.6392808930529283
retrain  8 :
	train: 0.769150873406623 0.6557863315035366 	test: 0.7563025210084033 0.6401895625288861


KeyboardInterrupt: 

In [ ]:
gtgp.print_model()

----------------GTGP-------------
Number of Trees: 15
Number of nodes: 51


In [ ]:
gtgp.stack

[( _add -> |11| |0| ),
 ( _minus -> |2| |6| ),
 ( _minus -> |3| |4| ),
 ( _divide -> |10| |2| ),
 ( _minus -> |6| |0| ),
 ( _multiply -> |5| |12| ),
 ( _divide -> |5| |10| ),
 ( _add -> |5| |10| ),
 ( _multiply -> |7| |10| ),
 ( _minus -> ( _add -> |1| |0| ) |6| ),
 ( _multiply -> |5| |4| ),
 ( _add -> |4| |5| ),
 ( _add -> |11| |4| ),
 ( _divide -> ( _add -> |12| |1| ) |2| ),
 ( _multiply -> |1| ( _minus -> |10| |5| ) )]

In [ ]:
print(classification_report(y_train,np.argmax(gtgp.train_p,axis=1),digits=5))
print(classification_report(y_test,np.argmax(gtgp.test_p,axis=1),digits=5))

              precision    recall  f1-score   support

           0    1.00000   0.87500   0.93333         8
           1    1.00000   0.66667   0.80000         3
           2    0.86957   1.00000   0.93023        20
           3    1.00000   1.00000   1.00000         4
           4    1.00000   0.80000   0.88889         5

    accuracy                        0.92500        40
   macro avg    0.97391   0.86833   0.91049        40
weighted avg    0.93478   0.92500   0.92289        40

              precision    recall  f1-score   support

           0    0.67259   0.43087   0.52525      6408
           1    0.19202   0.16311   0.17639      2716
           2    0.68465   0.78335   0.73068     15809
           3    0.70275   0.59723   0.64571      3250
           4    0.34072   0.42813   0.37946      3590

    accuracy                        0.60007     31773
   macro avg    0.51855   0.48054   0.49150     31773
weighted avg    0.60310   0.60007   0.59349     31773



# Decision Tree

In [5]:
from sklearn.tree import DecisionTreeClassifier

In [6]:
for i in range(30):
    X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=train_size,stratify=y, random_state=seeds[i])
    clf = DecisionTreeClassifier()
    clf.fit(X_train,y_train)

    num_trees = 1
    depth = clf.tree_.max_depth
    num_nodes = clf.tree_.node_count

    train_acc = accuracy_score(y_train,clf.predict(X_train))
    test_acc = accuracy_score(y_test,clf.predict(X_test))
    train_f1 = f1_score(y_train,clf.predict(X_train),average='macro')
    test_f1 = f1_score(y_test,clf.predict(X_test),average='macro')

    with open('./benchmark_DC/'+dataset+'.csv','a') as f:
        s = str(train_acc)+","+str(test_acc)+","+str(train_f1)+","+str(test_f1)+","+str(num_trees)+","+str(depth)+","+str(num_nodes)+"\n"
        f.writelines(s)

# XGBoost

In [7]:
import xgboost


In [8]:
for i in range(30):
    X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=train_size,stratify=y, random_state=seeds[i])
    # xgb = xgboost.XGBClassifier(min_child_weight=0,max_depth=3,n_estimators=100)
    # xgb = xgboost.XGBClassifier(min_child_weight=0,max_depth=4)
    xgb = xgboost.XGBClassifier()
    xgb.fit(X_train,y_train)

    import json

    def item_generator(json_input, lookup_key):
        if isinstance(json_input, dict):
            for k, v in json_input.items():
                if k == lookup_key:
                    yield v
                else:
                    yield from item_generator(v, lookup_key)
        elif isinstance(json_input, list):
            for item in json_input:
                yield from item_generator(item, lookup_key)

    def tree_depth(json_text):
        json_input = json.loads(json_text)
        depths = list(item_generator(json_input, 'depth'))
        return max(depths) + 1 if len(depths) != 0 else 1

    train_acc = accuracy_score(y_train,xgb.predict(X_train))
    test_acc = accuracy_score(y_test,xgb.predict(X_test))
    train_f1 = f1_score(y_train,xgb.predict(X_train),average='macro')
    test_f1 = f1_score(y_test,xgb.predict(X_test),average='macro')

    booster = xgb.get_booster()

    tree_df = booster.trees_to_dataframe()
    depths = [tree_depth(x) for x in booster.get_dump(dump_format = "json")]
    num_trees = len(depths)
    depth = np.average(depths)
    num_nodes = len(tree_df)

    with open('./benchmark_xgb/'+dataset+'.csv','a') as f:
        s = str(train_acc)+","+str(test_acc)+","+str(train_f1)+","+str(test_f1)+","+str(num_trees)+","+str(depth)+","+str(num_nodes)+"\n"
        f.writelines(s)

# GDBT

In [9]:
from sklearn.ensemble import GradientBoostingClassifier

In [10]:
for i in range(30):
    X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=train_size,stratify=y, random_state=seeds[i])
    clf = GradientBoostingClassifier()
    # clf = GradientBoostingClassifier()
    clf.fit(X_train,y_train)

    train_acc = accuracy_score(y_train,clf.predict(X_train))
    test_acc = accuracy_score(y_test,clf.predict(X_test))
    train_f1 = f1_score(y_train,clf.predict(X_train),average='macro')
    test_f1 = f1_score(y_test,clf.predict(X_test),average='macro')

    num_trees = len([ est for ests in clf.estimators_ for est in ests])
    depth = np.average([ max(1,est.tree_.max_depth) for ests in clf.estimators_ for est in ests])
    num_nodes = sum([ est.tree_.node_count for ests in clf.estimators_ for est in ests])

    with open('./benchmark_GBDT/'+dataset+'.csv','a') as f:
        s = str(train_acc)+","+str(test_acc)+","+str(train_f1)+","+str(test_f1)+","+str(num_trees)+","+str(depth)+","+str(num_nodes)+"\n"
        f.writelines(s)

# Random Forest

In [11]:
from sklearn.ensemble import RandomForestClassifier

In [12]:
for i in range(30):
    X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=train_size,stratify=y, random_state=seeds[i])
    rfc = RandomForestClassifier()
    rfc.fit(X_train,y_train)

    train_acc = accuracy_score(y_train,rfc.predict(X_train))
    test_acc = accuracy_score(y_test,rfc.predict(X_test))
    train_f1 = f1_score(y_train,rfc.predict(X_train),average='macro')
    test_f1 = f1_score(y_test,rfc.predict(X_test),average='macro')

    num_trees = len(rfc.estimators_)
    depth = np.average([est.tree_.max_depth for est in rfc.estimators_])
    num_nodes = sum([est.tree_.node_count for est in rfc.estimators_])

    with open('./benchmark_RF/'+dataset+'.csv','a') as f:
        s = str(train_acc)+","+str(test_acc)+","+str(train_f1)+","+str(test_f1)+","+str(num_trees)+","+str(depth)+","+str(num_nodes)+"\n"
        f.writelines(s)